### ISSUE TITLE
Ability to define paymaster sponsor logic in a configuration file

### ISSUE THREAD

**Issue by eerkaijun** [0xFableOrg/roll-op#39]
It would be nice if developers can define some common paymaster logic (e.g. whitelisted addresses) in a configuration file and the paymaster server will read directly from it. The current state is that developers have to manually write the logic in `paymaster/src/server.ts` file.

**Comment by norswap** [comment]
Context: https://github.com/0xFableOrg/simple-op-stack-rollup/pull/15#discussion_r1328451210
