### ISSUE TITLE
Spin up EIP-4337 infrastructure

### ISSUE THREAD

**Issue by norswap** [0xFableOrg/roll-op#4]
In our [project charter](https://app.charmverse.io/op-grants/proposals?id=a6e6bfb8-75bd-41bd-acb1-618c3c62e667), we committed to being able to spin EIP-4337 infrastructure alongside the rollup.

While this is not an immediate priority, the initial stages of that work is easily parallelizable with the rest of the work that is more rollup focused.

The goal here is simply to write simple scripts that enable spinning an EIP-4337 bundler and paymaster.

**Comment by eerkaijun** [comment]
Some open source bundler implementations that we could consider: 

- Bundler by Ethereum Foundation (https://github.com/eth-infinitism/bundler)
  - Written in Typescript
  - Seems to be a barebone implementation with limited functionality
- Alto bundler by Pimlico (https://github.com/pimlicolabs/alto)
  - Written in Typescript
- Bundler by Stackup (https://github.com/stackup-wallet/stackup-bundler)
  - Written in Go
- Voltaire bundler by Candide (https://github.com/candidelabs/voltaire)
  - Written in Python

I went through some of the codebase and documentations. I think the bundler by Pimlico seems to be quite performant with pretty good documentation. Typescript being type safe is another added bonus as compared to Python.

**Comment by cygaar** [comment]
@eerkaijun Voltaire might be good just to keep everything here in Python - not super opinionated here though

**Comment by eerkaijun** [comment]
> @eerkaijun Voltaire might be good just to keep everything here in Python - not super opinionated here though

Have used the stackup bundler for the initial version (good documentation), but we can revisit this later on!

**Comment by norswap** [comment]
Fixed by #15 and #42

Just remains to add the 4337 options in `roll.py`
