### ISSUE TITLE
Optimism is going to require go >= 1.20

### ISSUE THREAD

**Issue by upnodedev** [0xFableOrg/roll-op#56]
We have tried optimism [v1.1.6-rc.2](https://github.com/ethereum-optimism/optimism/releases/tag/v1.1.6-rc.2)

It requires go >= 1.20

<img width="751" alt="Screenshot 2023-09-28 111732" src="https://github.com/0xFableOrg/roll-op/assets/117493285/d6c5f6a5-9bab-4bfd-96d5-9c2eccd0b39b">

Otherwise, we can't build

**Comment by norswap** [comment]
Gotcha, we'll bump the minimum Go version required! 🫡

Haven't you tried building it with Go 1.21 btw? Someone tried and it was failing with the current commit we used, interested to see if 1.1.6 etc work with it.

**Comment by Inphi** [comment]
You'd run into further issues, not just with go (the monorepo now requires go 1.21), but with the devnet too. The monorepo recently changed how the devnet genesis is generated and is now incompatible with roll-op (sorry @norswap).

**Comment by norswap** [comment]
@Inphi We'll just use the new system then! Any useful info / pointers / documentation that would be helpful on that?

Is it the Go rewrite you told me about a while back?

**Comment by Inphi** [comment]
It's not quite the Go rewrite, this tooling was built a while ago for the bedrock regenesis. So we've had two ways to generate genesis configs - for devnet and "production" (i.e. CI, public devnets). We recently unified this so there's only one way, the same way it's done on prod.

The new way to do this is the following script: https://github.com/ethereum-optimism/optimism/blob/develop/op-node/cmd/genesis/cmd.go

```bash
go run op-node/cmd/main.go genesis --help
NAME:
   op-node genesis

USAGE:
   op-node genesis command [command options] [arguments...]

COMMANDS:
   l1       Generates a L1 genesis state file
   l2       Generates an L2 genesis file and rollup config suitable for a deployed network
   help, h  Shows a list of commands or help for one command

OPTIONS:

          --help, -h                          (default: false)
                show help
```
It can be used to generate both L1 and L2 genesis. Basic inputs are a base deployment config and preset account allocs. Here's an example of the script being used to build the devnet - https://github.com/ethereum-optimism/optimism/blob/5e6b7f1edd1398858c3dcdcf250a977cd70d0cb6/bedrock-devnet/devnet/__init__.py#L177.

**Comment by upnodedev** [comment]
I think we should not go beyond version 1.1.4 now as they are going forward superchain by sharing l1 contract as a discussion in https://github.com/ethereum-optimism/optimism/pull/7449
