### ISSUE TITLE
Clean need remove explorer service containers

### ISSUE THREAD

**Issue by GrapeBaBa** [0xFableOrg/roll-op#62]
We may need removing explorer service containers when #61 merged? @norswap

**Comment by norswap** [comment]
Right now our clean commands don't remove any of the built binaries.
What are those containers exactly, are those things we need to run blockscout?

The problem with `clean` is that it's hard to know what's desired between:
1. delete intermediate build outputs (that can be safely deleted)
2. delete generated config files, deployment info, databases, ... (there are the things that would change if we do a new deployment / generation)
3. delete build software (that will be rebuilt similarly unless updating)

Right we do (1) and (2) for `clean` and just (1) for `clean-build`. We could add something that does all three, though not sure how useful that is.
