### ISSUE TITLE
support op-node latest version(v1.3.1)

### ISSUE THREAD

**Issue by thinkAfCod** [0xFableOrg/roll-op#65]
The latest version of the op-node for Optimism, v1.3.1, has arrived.
The way `roll-op` initializes L1 nodes is now significantly different from the way L1 nodes are initialized in the latest version of `op-node` Corresponding modifications are needed.

**Comment by norswap** [comment]
It's definitely on the docket 🫡

**Comment by norswap** [comment]
I'm not entirely sure why, but I picked v1.3.0 as a target when I started working on this. It should probably be pretty easy to further upgrade to 1.3.1.
