### ISSUE TITLE
Upgrade paymaster support to 0.7

### ISSUE THREAD

**Issue by pegahcarter** [0xFableOrg/roll-op#97]
Two weeks ago eth-infinitism released [v0.7.0](https://github.com/eth-infinitism/account-abstraction/releases/tag/v0.7.0).  I recommend updating dependencies to ensure support.

cc @vintageplayer

**Comment by norswap** [comment]
Thanks! We definitely want to do that — there are a number of things that need to be updated right now (including the OP stack itself), but we'll get this sorted out.

Do you want to take a crack at it by any chance?

cc @eerkaijun

**Comment by pegahcarter** [comment]
Sure! I can in the following days.

**Comment by norswap** [comment]
That'd be great!
